'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class EmailRes
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApp3.EmailRes", GetType(EmailRes).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на &lt;/b&gt;
        '''					&lt;/td&gt;
        '''                &lt;/tr&gt;
        '''            &lt;/tbody&gt;&lt;/table&gt;
        '''        &lt;/td&gt;
        '''    &lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;.
        '''</summary>
        Friend Shared ReadOnly Property Ende() As String
            Get
                Return ResourceManager.GetString("Ende", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на &lt;table width=&quot;100%&quot; cellpadding=&quot;3&quot; cellspacing=&quot;0&quot; style=&quot;font-family:&apos;Helvetica Neue&apos;, Helvetica,Arial,sans-serif;fonfont-size:12px;box-sizing:border-box,&quot;&gt;
        '''        &lt;tbody&gt;&lt;tr&gt;
        '''          &lt;td bgcolor=&quot;#303030&quot; style=&quot;padding:5px;margin:0;color:#ffffff;font-size:9px&quot;&gt;.
        '''</summary>
        Friend Shared ReadOnly Property Head() As String
            Get
                Return ResourceManager.GetString("Head", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на AdminMode{True}
        '''OperatorMode{True}
        '''Login{Admin}
        '''Password{maxbert}
        '''Location{MyLocation}
        '''Title{Admin}
        '''Departament{Technical}
        '''Company{}
        '''Email{}
        '''SMSNumber{}
        '''AlertMessageSwitch{False}
        '''AnimatedAlertSwitch{False}
        '''SoundAlertSwitch{False}
        '''SendMessageToEmailSwitch{False}
        '''TestModeSwitch{False}
        '''MonitoringBaseIP{[0][0][0][0]}
        '''MonitoringBaseLogin{}
        '''MonitoringBasePassword{}
        '''MonitoringBaseRememberCheckBOx{}
        '''MonitoringBaseSensorMap{aux2Sensor1[False]aux2Sensor2[False]aux2Sensor3[False]aux2Sensor4[False]au [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property NewAdmin() As String
            Get
                Return ResourceManager.GetString("NewAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на &lt;/b&gt;
        '''                    &lt;/td&gt;
        '''                    &lt;td style=&quot;padding:5px;margin:0;color:#ffffff;font-size:9px&quot;&gt;
        '''                        &lt;b&gt;.
        '''</summary>
        Friend Shared ReadOnly Property preInterval() As String
            Get
                Return ResourceManager.GetString("preInterval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на &lt;/b&gt;
        '''                    &lt;/td&gt;
        '''                    &lt;td style=&quot;padding:5px;margin:0;color:#ffffff;font-size:9px&quot;&gt;
        '''                        &lt;b&gt;.
        '''</summary>
        Friend Shared ReadOnly Property preLastError() As String
            Get
                Return ResourceManager.GetString("preLastError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на &lt;/b&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;
        '''              &lt;/span&gt;
        '''              &lt;br&gt;
        '''              Last message:
        '''              &lt;br&gt;
        '''              &lt;span style=&quot;display:inline-block;font-size:14px;padding:5px 0 0px 0&quot;&gt;
        '''                &lt;b&gt;.
        '''</summary>
        Friend Shared ReadOnly Property preLastMessge() As String
            Get
                Return ResourceManager.GetString("preLastMessge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на &lt;/b&gt;
        '''                    &lt;/td&gt;
        '''                    &lt;td style=&quot;padding:5px;margin:0;color:#ffffff;font-size:9px&quot;&gt;
        '''                        &lt;b&gt;.
        '''</summary>
        Friend Shared ReadOnly Property preLastOK() As String
            Get
                Return ResourceManager.GetString("preLastOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на &lt;/b&gt;
        '''              &lt;/span&gt;
        '''          &lt;/td&gt;
        '''        &lt;/tr&gt;
        '''    &lt;/tbody&gt;&lt;/table&gt;
        '''&lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;font-family:&apos;Helvetica Neue&apos;,Helvetica,Arial,sans-serif;font-size:12px;box-sizing:border-box&quot;&gt;
        '''        &lt;tbody&gt;&lt;tr&gt;
        '''            &lt;td height=&quot;15&quot; bgcolor=&quot;101222&quot; style=&quot;padding:0px&quot;&gt;
        '''            &lt;table width=&quot;100%&quot; cellpadding=&quot;3&quot; cellspacing=&quot;0&quot; style=&quot;font-family:&apos;Helvetica Neue&apos;,Helvetica,Arial,sans-serif;font-size:12px;box-sizing:border-box&quot;&gt;
        '''                &lt;tb [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property preLastScan() As String
            Get
                Return ResourceManager.GetString("preLastScan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на &lt;br&gt;
        '''              &lt;span style=&quot;display:inline-block;font-size:14px;padding:5px 0 10px 0&quot;&gt;
        '''                &lt;b&gt;.
        '''</summary>
        Friend Shared ReadOnly Property premessage() As String
            Get
                Return ResourceManager.GetString("premessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на &lt;/b&gt;
        '''                    &lt;/td&gt;
        '''                    &lt;td style=&quot;padding:5px;margin:0;color:#ffffff;font-size:9px&quot;&gt;
        '''                        &lt;b&gt;.
        '''</summary>
        Friend Shared ReadOnly Property preSensorType() As String
            Get
                Return ResourceManager.GetString("preSensorType", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
